CREATE TABLE animes (
    id BIGINT NOT NULL AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(50) NOT NULL,
    anime VARCHAR(50) NOT NULL,
    autor VARCHAR(50)NOT NULL,
    genero VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
);